require 'slack-ruby-bot'
require 'gabe-botler/bot'
require 'gabe-botler/about'
require 'gabe-botler/responses/responses'
require 'gabe-botler/commands/advice'
require 'gabe-botler/commands/work'
require 'gabe-botler/commands/gabe'
require 'gabe-botler/commands/thoughts'